# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Nzg0ZGNkMjlhOTUzYzdmM2NjMzhlYmZkZTFhMDM3NTJmMGViMDRiMjBhYTkyNzRmMjI1MGI5MDYxZDRlZjVkZmU2OTBkY2RkMDgzNWQ0NDVmYmI3NmRmMWI5MmUxNjYyYjQ1Y2U0MWMzNTY1OTg0ZThkNGJiYWE0Yzc3ZTVkYzM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
